// dogs image path list

import '../models/model_pet_details.dart';

List<PetDetails> dogDetailsList = [
  PetDetails(
    id: 1,
    imagePath: 'images/shihtzu_1.png',
    name: 'Sally',
    age: '25 Days',
    price: '18000',
    breed: 'Shih Tzu',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 2,
    imagePath: 'images/shihtzu_2.jpeg',
    name: 'Bellie',
    age: '1 month',
    price: '16000',
    breed: 'Shih Tzu',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 3,
    imagePath: 'images/shihtzu_3.jpeg',
    name: 'Brew',
    age: '3 months 15 Days',
    price: '15000',
    breed: 'Shih Tzu',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 4,
    imagePath: 'images/shihtzu_4.jpeg',
    name: 'Gin',
    age: '4 months',
    price: '16500',
    breed: 'Shih Tzu',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 5,
    imagePath: 'images/pomer_1.png',
    name: 'Tail',
    age: '1 month',
    price: '28000',
    breed: 'Pomeranian',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 6,
    imagePath: 'images/pomer_2.png',
    name: 'Fluffy',
    age: '1 Month 10 Days',
    price: '26000',
    breed: 'Pomeranian',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 7,
    imagePath: 'images/pomer_3.png',
    name: 'Bunny',
    age: '3 months',
    price: '23000',
    breed: 'Pomeranian',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 8,
    imagePath: 'images/pomer_4.png',
    name: 'Moss',
    age: '2 months 25 Days',
    price: '24000',
    breed: 'Pomeranian',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 9,
    imagePath: 'images/pug_1.png',
    name: 'Gunzo',
    age: '4 months',
    price: '30000',
    breed: 'Pug',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 10,
    imagePath: 'images/pup_1.jpeg',
    name: 'Fort',
    age: '3 months',
    price: '29500',
    breed: 'Yorkie',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 11,
    imagePath: 'images/gr_1.jpeg',
    name: 'Billie',
    age: '3 months',
    price: '150000',
    breed: 'Golden Retriever',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 12,
    imagePath: 'images/gr_2.png',
    name: 'Loan',
    age: '6 months',
    price: '19000',
    breed: 'Golden Retriever',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 13,
    imagePath: 'images/gr_3.jpeg',
    name: 'Mocha',
    age: '1 month 15 Days',
    price: '20000',
    breed: 'Golden Retriever',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 14,
    imagePath: 'images/gr_4.jpeg',
    name: 'Tiny',
    age: '1 month',
    price: '14500',
    breed: 'Golden Retriever',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 15,
    imagePath: 'images/gs_1.jpeg',
    name: 'Tokio',
    age: '1 month 25 Days',
    price: '18000',
    breed: 'German Shepherd',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 16,
    imagePath: 'images/gs_2.png',
    name: 'Shiny',
    age: '3 months',
    price: '165000',
    breed: 'German Shepherd',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 17,
    imagePath: 'images/gs_3.jpeg',
    name: 'Coco',
    age: '2 months 18 Days',
    price: '17500',
    breed: 'German Shepherd',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 18,
    imagePath: 'images/gs_4.png',
    name: 'Skillet',
    age: '2 months',
    price: '15000',
    breed: 'German Shepherd',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 19,
    imagePath: 'images/husky_2.png',
    name: 'Brownie',
    age: '2 months',
    price: '30000',
    breed: 'Husky',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 20,
    imagePath: 'images/husky_4.png',
    name: 'Goofy',
    age: '3 months',
    price: '30000',
    breed: 'Husky',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 21,
    imagePath: 'images/husky_5.jpeg',
    name: 'Lazie',
    age: '1 month 18 Dys',
    price: '32000',
    breed: 'Husky',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 22,
    imagePath: 'images/lab_2.jpeg',
    name: 'Sibbie',
    age: '2 months',
    price: '20000',
    breed: 'Labrador',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 23,
    imagePath: 'images/lab_1.jpeg',
    name: 'Button',
    age: '1 month 27 Days',
    price: '25000',
    breed: 'Labrador',
    isAdopted: false,
    species: Species.dog,
  ),
  PetDetails(
    id: 24,
    imagePath: 'images/dh_1_4.png',
    name: 'Chocolate',
    age: '1 month 27 Days',
    price: '25000',
    breed: 'Dachshund',
    isAdopted: false,
    species: Species.dog,
  ),
];

List<PetDetails> catDetailsList = [
  PetDetails(
    id: 25,
    imagePath: 'images/bsh_1.png',
    name: 'Penny',
    age: '25 Days',
    price: '18000',
    breed: 'British Short-hair',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 26,
    imagePath: 'images/bsh_2.png',
    name: 'Nord',
    age: '1 month',
    price: '16000',
    breed: 'British Short-hair',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 27,
    imagePath: 'images/bsh_3.jpeg',
    name: 'Gray',
    age: '3 months 15 Days',
    price: '15000',
    breed: 'British Short-hair',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 28,
    imagePath: 'images/bsh_4.jpeg',
    name: 'Bun',
    age: '4 months',
    price: '16500',
    breed: 'British Short-hair',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 29,
    imagePath: 'images/esh_1.jpeg',
    name: 'Folly',
    age: '1 month',
    price: '28000',
    breed: 'Exotic Short-hair',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 30,
    imagePath: 'images/esh_2.jpeg',
    name: 'Grain',
    age: '1 Month 10 Days',
    price: '26000',
    breed: 'Exotic Short-hair',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 31,
    imagePath: 'images/esh_3.png',
    name: 'Juno',
    age: '3 months',
    price: '23000',
    breed: 'Exotic Short-hair',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 32,
    imagePath: 'images/mc_1.png',
    name: 'Moses',
    age: '2 months 25 Days',
    price: '24000',
    breed: 'Maine Coon',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 33,
    imagePath: 'images/mc_2.png',
    name: 'Shoe',
    age: '4 months',
    price: '30000',
    breed: 'Maine Coon',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 34,
    imagePath: 'images/mc_3.jpeg',
    name: 'Gineger',
    age: '3 months',
    price: '29500',
    breed: 'Maine Coon',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 35,
    imagePath: 'images/mc_4.jpeg',
    name: 'Lion',
    age: '3 months',
    price: '150000',
    breed: 'Maine Coon',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 36,
    imagePath: 'images/pers_1.png',
    name: 'Pillow',
    age: '6 months',
    price: '19000',
    breed: 'Persian',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 37,
    imagePath: 'images/pers_2.jpeg',
    name: 'Coffee',
    age: '1 month 15 Days',
    price: '20000',
    breed: 'Persian',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 38,
    imagePath: 'images/pers_3.png',
    name: 'Snowey',
    age: '1 month',
    price: '14500',
    breed: 'Persian',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 39,
    imagePath: 'images/pers_4.png',
    name: 'BooBoo',
    age: '1 month 25 Days',
    price: '18000',
    breed: 'Persian',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 40,
    imagePath: 'images/ragdoll_1.jpeg',
    name: 'Jimmy',
    age: '3 months',
    price: '165000',
    breed: 'Rag Doll',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 41,
    imagePath: 'images/ragdoll_2.jpeg',
    name: 'Spots',
    age: '2 months 18 Days',
    price: '17500',
    breed: 'Rag Doll',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 42,
    imagePath: 'images/ragdoll_3.png',
    name: 'Kappy',
    age: '2 months',
    price: '15000',
    breed: 'Rag Doll',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 43,
    imagePath: 'images/ragdoll_4.png',
    name: 'Jin',
    age: '2 months',
    price: '30000',
    breed: 'Rag Doll',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 44,
    imagePath: 'images/sf_1.jpeg',
    name: 'Pepper',
    age: '3 months',
    price: '30000',
    breed: 'Scottish Fold',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 45,
    imagePath: 'images/stray_3.png',
    name: 'Leo',
    age: '1 month 18 Dys',
    price: '32000',
    breed: 'Stray',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 46,
    imagePath: 'images/stray_1.png',
    name: 'Shadow',
    age: '2 months',
    price: '20000',
    breed: 'Stray',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 47,
    imagePath: 'images/sf_4.jpeg',
    name: 'Bao',
    age: '1 month 27 Days',
    price: '25000',
    breed: 'Scottish Fold',
    isAdopted: false,
    species: Species.cat,
  ),
  PetDetails(
    id: 48,
    imagePath: 'images/sf_3.png',
    name: 'Max',
    age: '1 month 27 Days',
    price: '28000',
    breed: 'Scottish Fold',
    isAdopted: false,
    species: Species.cat,
  ),
];
